neptoon/nepton/articles/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


#nepton,nepton,nepton,...
app_name = "nep_blog"
urlpatterns = [
    path('articles/', views.ar_list),
    path('articles/<slug:slug>', views.page),
    path('', views.home,name="home"),
    path('post/<slug:slug>', views.post ,name="post"),
    path('about-me/', views.about),
]

neptoon/nepton/nepton/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls'),name="articles"),
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

neptoon/nepton/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls'),name="articles"),
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

neptoon/nepton/articles/models.py
from django.db import models
from django.utils import timezone

class Category(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100,unique=True)
    status = models.BooleanField(default=True , verbose_name="show this ?")
    position = models.IntegerField(verbose_name="position")

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.title

#nepton,nepton,nepton,...

class articles(models.Model):
    STATUS_CHOICES=(
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    title=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100,unique=True)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to="images")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    Category = models.ManyToManyField(Category, verbose_name="Category")
    #body=models.TextField()
    #date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

neptoon/nepton/articles/views.py
from django.shortcuts import render
from . import models
def home(request):
    articles= models.articles.objects.filter(status="p").order_by('-updated')
    args={'articles':articles}
    return render(request,'articles/home.html',args)

#nepton,nepton,nepton,...

def ar_list(request):
    articles= models.articles.objects.filter(status="p").order_by('-updated')
    args={'articles':articles}
    return render(request,'articles/ar_list.html',args)

#nepton,nepton,nepton,...

def page(request, slug):
    articles= models.articles.objects.get(slug=slug)
    args={'articles':articles}
    return render(request,'articles/page.html',args)


def post(request, slug):
    articles= models.articles.objects.get(slug=slug)
    args={'articles':articles}
    return render(request,'articles/post.html',args)

def about(request):
    return render(request,'articles/about.html')

neptoon/nepton/nepton/views.py
from django.shortcuts import render

neptoon/nepton/views.py
from django.shortcuts import render

neptoon/nepton/articles/templates/articles/about.html
{% extends 'articles/base.html' %}


{% load static %}


{% block header %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "nepton/img/about-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">I'm z3os. not Enough ? :)</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}



{% block main %}
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>hi My name is Abolfazl Majdi!</p>
        <p>I'm Back End developer . I code with Django . Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.I'll write an article about this framework later. ِ</p>
        <p>I can coding with c/c++ too but for now, I write more code with Python and Ruby !</p>
        <p>you can call me with These ways :</p>
        <ul>
            <li>Phone: 9374977914</li>
            <li>Email: <a href="mailto:abolfazlmajidi1382@gmail.com">abolfazlmajidi1382@gmail.com</a></li>
            <li>Twitter: Abolfazl Majidi</li>
            <li>Telegram: @ss727</li>
        </ul>
      </div>
    </div>
  </div>
  {% endblock %}

neptoon/nepton/articles/templates/articles/ar_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Articles</title>
    <meta name="description" content="abolfazl majidi,majidis web page">
    <meta name="viewport" content="
    width=device-width,initial-scale=1.0">

<!-- #fafafa -->
    <style>
      html {
        padding-top: 60px;
      }
      .title {
        color: #120445;

        padding: 0px 0px 15px 10px;
        margin: 0px;

        margin-right: 20px;
      }
      .box {
        background: #e6e6e6;
        box-shadow: 0 4px 2px -2px rgba(0,0,0,.05);
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        z-index: 100;
      }
      #asli {
        font-size: 80px;
      }
      .class_img {
        float: left;
        font-family:Century

      }
      .clearfix:after {
        visibility: hidden;
        display: block;
        font-size: 0px;
        content: " ";
        clear: both;
        height: 0px;
      }
      #rah nav ul {
        list-style: none;
        padding: 0;
        margin: 0;

      }
      #rah nav ul li {
        float: left;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 20px
      }
      #rah nav ul li a {
        text-decoration: none;
      }
      #rah nav ul li a:hover{
        background: #00FF7F;
        border-radius:5px;
      }
      .cont {
        width: 960px;
        margin: 0 auto;
      }
      .card {
        background: #f7f7f7;
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #e1e1e1;
        margin-top: 20px;
        padding-bottom: 30px;
        padding-top: 30px;
        padding-left: 10px
      }




      #post{
        position: relative;
      }
      #img_post{
        position: absolute;
        left: 790px;
        top: 5px;
      }
    </style>




    <header id="rah" class="box clearfix">
      <p class="class_img title" style="margin-right: 10px;font-size: 45px;">Articles</p>
      <nav>
        <ul>
          <li><a target="_blank" href="http://127.0.0.1:8000">Home</a></li>
          <li><a target="_blank" href="http://127.0.0.1:8000/about/">About Me</a></li>
          <li><a target="_blank" href="http://127.0.0.1:8000/articles/">articles</a></li>
        </ul>
      </nav>
      <a href="http://127.0.0.1:8000/media/images/hgh.png">
        <img  style=" width: 60px;height: 60px;border: 1px solid black;border-radius:100px;margin: 0;float: right;"
        src="http://127.0.0.1:8000/media/images/hgh.png">
      </a>
      <h6 style="float: right;">Abolfazl Majidi</h6>
    </header>
  </head>





  <body>
      {% for a in articles %}
      <div class="cont card" id="post">
        <h2 style="margin: 0;"><a style="text-decoration: none;color: black " href="{{a.slug}}">{{a.title}}</a></h2>
              <img id="img_post" style=" width: 190px;height: 190px;border: 1px solid black;border-radius:10px;
              margin-left: 0;" src={{a.thumbnail.url}}>

        <p style="display: block;margin-right: 300px">{{a.description}}</p>
        <small style="font-size: 4px;margin: 0">created in : {{a.created}}</small><br>
        <small style="font-size: 4px;margin: 0">updated in : {{a.updated}}</small>


      </div>
      {% endfor %}

  </body>

</html>
<!--  <hr style="border: 2px solid black;">

-->

neptoon/nepton/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Nepton{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'nepton/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'nepton/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'nepton/css/clean-blog.min.css' %}" rel="stylesheet">
  <link href="{% static 'nepton/css/rtl.css' %}" rel="stylesheet">

</head>

<body style="direction: rtl;text-align: right;font-family:'Sahel';">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="http://nepton.pythonanywhere.com/">Nepton</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="http://nepton.pythonanywhere.com/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://nepton.pythonanywhere.com/about-me/">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% block header %}

{% endblock %}


{% block main %}

{% endblock %}
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/majidi_abolfazl">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>



            <li class="list-inline-item">
              <a href="https://github.com/salam727">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>

          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

neptoon/nepton/articles/templates/articles/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

neptoon/nepton/articles/templates/articles/home.html
{% extends 'articles/base.html' %}


{% load static %}


{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static "nepton/img/gha.jpg" %}')">
                         <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1 style="font-family:Bell MT">Nepton</h1><hr>
          <span class="subheading" style="font-family:Bradley Hand ITC">A way to heaven</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}



{% block main %}
<!-- Main Content  truncatechars -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

      {% for a in articles %}
      <div class="post-preview">
        <a href="{% url 'nep_blog:post' a.slug %}">
          <h2 class="post-title">
            {{a.title}}
          </h2>
          <h3 class="post-subtitle">
            {{a.description | truncatechars:80}}
          </h3>
        </a>

        <div>
          {% for cat in a.Category.all %}
          <a href="#">#{{cat.title}}</a>
          {% endfor %}
        </div>

        <p class="post-meta">Posted by
          <a href="#">z3os</a>
          on {{a.created}}</p>

      </div>
      <hr><br>

{% endfor %}
      <!-- Pager -->
      <div class="clearfix">

        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>

<!-- Main Content end -->
{% endblock %}

neptoon/nepton/articles/templates/articles/page.html
hello

neptoon/nepton/articles/templates/articles/post.html
{% extends 'articles/base.html' %}


{% block title %} | article{% endblock %}


{% load static %}


{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{{articles.thumbnail.url}}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>{{articles.title}}</h1>
          <h2 class="subheading">{{articles.description | truncatewords:20}}</h2>
          <span class="meta">Posted by
            <a href="#">z3os</a>
            on {{articles.created}}</span>
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}






{% block main %}
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        {{articles.description|linebreaks}}

      </div>
    </div>
  </div>
</article>
{% endblock %}

neptoon/nepton/nepton/templates/nepton/home-copy.html
{% extends 'nepton/base.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/gha.jpg')">
                         <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}





{% block main %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview">
        <a href="post.html">


          <h2 class="post-title">
            Man must explore, and this is exploration at its greatest
          </h2>
          <h3 class="post-subtitle">
            Problems look mighty small from 150 miles up
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on September 24, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
          </h2>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on September 18, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            Science has not yet mastered prophecy
          </h2>
          <h3 class="post-subtitle">
            We predict too much for the next year and yet far too little for the next ten.
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on August 24, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            Failure is not an option
          </h2>
          <h3 class="post-subtitle">
            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on July 8, 2019</p>
      </div>
      <hr>


      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

neptoon/nepton/templates/nepton/home-copy.html
{% extends 'nepton/base.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('img/gha.jpg')">
                         <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}





{% block main %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview">
        <a href="post.html">


          <h2 class="post-title">
            Man must explore, and this is exploration at its greatest
          </h2>
          <h3 class="post-subtitle">
            Problems look mighty small from 150 miles up
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on September 24, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
          </h2>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on September 18, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            Science has not yet mastered prophecy
          </h2>
          <h3 class="post-subtitle">
            We predict too much for the next year and yet far too little for the next ten.
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on August 24, 2019</p>
      </div>
      <hr>


      <div class="post-preview">
        <a href="post.html">
          <h2 class="post-title">
            Failure is not an option
          </h2>
          <h3 class="post-subtitle">
            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
          </h3>
        </a>
        <p class="post-meta">Posted by
          <a href="#">Start Bootstrap</a>
          on July 8, 2019</p>
      </div>
      <hr>


      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}